### ISSUE TITLE
[Enhancement] Add test cases to the repo

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/automation-app#6]
We need to add test cases to this repo.

The official probot framework uses `vitest` to handle tests in which I replaced with `jest`.

Will need to take a look and add some example test cases.

------

PRs:
* https://github.com/opensearch-project/automation-app/pull/11

**Comment by peterzhuamazon** [comment]
CodeCov Issues: 
* https://github.com/codecov/feedback/issues/525

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/refa), [3](https://github.com/andrross), [4](https://github.com/krisfreedain)]
